"""add_email_verification_and_update_models

Revision ID: c588da365e0d
Revises: 5b12904a2a83
Create Date: 2026-04-09 14:50:21.092084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c588da365e0d'
down_revision: Union[str, Sequence[str], None] = '5b12904a2a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('why_goal', sa.Text(), nullable=True))
    op.add_column('goals', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('goals_hobby_id_fkey'), 'goals', type_='foreignkey')
    op.drop_column('goals', 'hobby_id')
    op.add_column('hobbies', sa.Column('beginner_description', sa.Text(), nullable=True))
    op.add_column('hobbies', sa.Column('intermediate_description', sa.Text(), nullable=True))
    op.add_column('hobbies', sa.Column('advanced_description', sa.Text(), nullable=True))
    op.alter_column('hobbies', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_likes_portfolio_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.add_column('portfolio_works', sa.Column('hobby_id', sa.Integer(), nullable=True))
    op.add_column('portfolio_works', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('portfolio_works', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('portfolio_works', 'activity_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'did_hobby'::character varying"))
    op.create_foreign_key(None, 'portfolio_works', 'hobbies', ['hobby_id'], ['id'])
    op.add_column('user_activity', sa.Column('activity_type', sa.String(), nullable=False))
    op.add_column('user_activity', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('user_activity', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('user_activity', 'hobby_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_user_activity_activity_date'), 'user_activity', ['activity_date'], unique=False)
    op.create_foreign_key(None, 'user_activity', 'portfolio_works', ['post_id'], ['id'])
    op.add_column('user_hobbies', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('user_hobbies', sa.Column('frequency_per_week', sa.Integer(), nullable=True))
    op.add_column('user_hobbies', sa.Column('frequency_per_month', sa.Integer(), nullable=True))
    op.add_column('user_hobbies', sa.Column('experience_description', sa.Text(), nullable=True))
    op.add_column('user_hobbies', sa.Column('why_this_hobby', sa.Text(), nullable=True))
    op.add_column('user_hobbies', sa.Column('looking_for_in_partner', sa.Text(), nullable=True))
    op.add_column('user_hobbies', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.create_unique_constraint('unique_user_hobby', 'user_hobbies', ['user_id', 'hobby_id'])
    op.drop_constraint(op.f('user_hobbies_level_id_fkey'), 'user_hobbies', type_='foreignkey')
    op.drop_column('user_hobbies', 'level_id')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires', sa.DateTime(), nullable=True))
    
    # ✅ СОЗДАЁМ таблицу email_verifications (внутри функции upgrade!)
    op.create_table('email_verifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('code', sa.String(length=6), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('is_used', sa.Boolean(), nullable=True),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_id'), 'email_verifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ✅ Удаляем таблицу email_verifications (внутри функции downgrade!)
    op.drop_index(op.f('ix_email_verifications_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    
    op.drop_column('users', 'verification_code_expires')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    op.add_column('user_hobbies', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_hobbies_level_id_fkey'), 'user_hobbies', 'levels', ['level_id'], ['id'])
    op.drop_constraint('unique_user_hobby', 'user_hobbies', type_='unique')
    op.drop_column('user_hobbies', 'is_public')
    op.drop_column('user_hobbies', 'looking_for_in_partner')
    op.drop_column('user_hobbies', 'why_this_hobby')
    op.drop_column('user_hobbies', 'experience_description')
    op.drop_column('user_hobbies', 'frequency_per_month')
    op.drop_column('user_hobbies', 'frequency_per_week')
    op.drop_column('user_hobbies', 'experience_level')
    op.drop_constraint(None, 'user_activity', type_='foreignkey')
    op.drop_index(op.f('ix_user_activity_activity_date'), table_name='user_activity')
    op.alter_column('user_activity', 'hobby_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_activity', 'created_at')
    op.drop_column('user_activity', 'post_id')
    op.drop_column('user_activity', 'activity_type')
    op.drop_constraint(None, 'portfolio_works', type_='foreignkey')
    op.alter_column('portfolio_works', 'activity_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'did_hobby'::character varying"))
    op.drop_column('portfolio_works', 'updated_at')
    op.drop_column('portfolio_works', 'is_public')
    op.drop_column('portfolio_works', 'hobby_id')
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_likes_portfolio_id'), 'likes', ['portfolio_id'], unique=False)
    op.alter_column('hobbies', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('hobbies', 'advanced_description')
    op.drop_column('hobbies', 'intermediate_description')
    op.drop_column('hobbies', 'beginner_description')
    op.add_column('goals', sa.Column('hobby_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('goals_hobby_id_fkey'), 'goals', 'hobbies', ['hobby_id'], ['id'])
    op.drop_column('goals', 'is_public')
    op.drop_column('goals', 'why_goal')
    # ### end Alembic commands ###