"""add description column to hobbies

Revision ID: 7fd031872ac9
Revises: a612a6b0895e
Create Date: 2026-03-11 15:12:04.436722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd031872ac9'
down_revision: Union[str, Sequence[str], None] = 'a612a6b0895e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hobbies', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hobbies', 'description')
    # ### end Alembic commands ###
