"""add description and created_at to hobbies

Revision ID: 970cbea13232
Revises: 7fd031872ac9
Create Date: 2026-03-11 15:20:00.073305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970cbea13232'
down_revision: Union[str, Sequence[str], None] = '7fd031872ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hobbies', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hobbies', 'created_at')
    # ### end Alembic commands ###
